### PR TITLE
Run clang-format on entire repo

### PR DESCRIPTION
**Pull request by davetcoleman**
In reviewing https://github.com/ros-planning/moveit_kinematics_tests/pull/10 I realized this repo has not been clang-formatted as the rest of moveit has, so I ran the script here in a separate PR so that my request [here](https://github.com/ros-planning/moveit_kinematics_tests/pull/10#discussion_r123886929) doesn't cause too many changes in the same PR. This should be merged first, and @nsnitish should run clang-format on his PR also

### CODE REVIEW

**Comment by jrgnicho** [comment]
@davetcoleman looks like the fask ik code didn't get formatted correctly.

**Comment by jrgnicho** [comment]
@davetcoleman  I had to run clang twice in order get all the files formatted correctly.  I created  PR #13  in order to address the formatting issue along with other issues that prevented travis-ci from passing.

**Comment by davetcoleman** [comment]
Ah I was using an old version of the moveit clang format file (I changed it a while back but had two versions on my computer). I have fixed this PR. I think we should still merge this first so your other PR can be reviewed without the formatting changes.

**Comment by jrgnicho** [comment]
Sounds good to me.  I'll wait until the travis check finishes.

**Comment by davetcoleman** [comment]
Looks like travis will not pass because the first two non-clang-format tests are failing before the clang-format test passes. I'll just close this and go with your fix :)

**Pull request closed without merging**
