### PR TITLE
Updated ikfast plugins for kuka_kr210 and motoman_sia20d

### PR DESCRIPTION
**Pull request by nsnitish**
Currently in this repo, [two testcases are failing](https://travis-ci.org/ros-planning/moveit_kinematics_tests/jobs/259805565#L884) due to a new test introduced in #10 . This PR updates the plugins according to  ros-planning/moveit/pull/537

### CODE REVIEW

**Comment by nsnitish** [comment]
I think there is difference in formatting as well. Tried running clang format but these files are not changing. Do we really need to change the format of the auto-generated files?

**Comment by jrgnicho** [comment]
It's somewhat hard to tell what changed as it seems that this PR also contains formatting changes.

**Comment by nsnitish** [comment]
@jrgnicho ! I tried clang format but I am not sure why it's not working. Major change is for the getPositionIK method in the moveit_plugins for [motoman sia20d](https://github.com/ros-planning/moveit_kinematics_tests/pull/15/files#diff-5b4a60432a52aa253a822426263ce322R1009) and [kuka_kr210](https://github.com/ros-planning/moveit_kinematics_tests/pull/15/files#diff-b6241a0d684035414fbe206903a78f18R1009). Also, the Travis is passing now due to plugin fix.

**Comment by jrgnicho** [comment]
Could you undo the formatting and just commit the relevant changes?

**Comment by nsnitish** [comment]
IKFAST plugins are auto-generated files as I followed [this tutorial](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/ikfast_tutorial.html). I tried clang formatting these auto-generated files but they aren't changing.

**Comment by nsnitish** [comment]
I can just push the changes by comparing them at my end . But do we really need to change the format of the auto-generated files?

**Comment by jrgnicho** [comment]
Sure, I wouldn't worry about the formatting changes to the auto-generated files.  That should be addressed separately.

**Comment by davetcoleman** [comment]
*top secret* to by pass clang format on the CI server just use

// clang-format off
// clang-format on

Seems ok for auto generated files, but I don't understand why you wouldn't be able to get matching results on your local computer. Probably because you are missing the ``.clang-format`` file in the file structure of this repo. It works for ``moveit`` because we have one committed there, but you need to copy it manually to this repo

**Comment by nsnitish** [comment]
I tried that as well. I am not sue why it isn't working. Currently, the PR has the clang formatted files and you can review it if possible.

**Pull request merged**
